name: Python CI with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      packages: write

    steps:
      # 1. Fazer checkout do código
      - uses: actions/checkout@v4

      # 2. Configurar o Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 3. Instalar dependências
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Login no Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "eduyaginuma"
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5. Configurar Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 6. Construir e empurrar a imagem Docker para o Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: eduyaginuma/flask-app:${{ github.sha }}

      # 7. Fazer o deploy no servidor remoto via SSH
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_TEST }}
          username: "ubuntu"
          key: ${{ secrets.KEY_TEST }}
          port: 22
          script: |
            docker stop flask_app || true
            docker rm --force flask_app || true
            docker pull eduyaginuma/flask-app:${{ github.sha }}
            docker run -d -p 80880:8080 --network=todo --name flask_app eduyaginuma/flask-app:${{ github.sha }}
